version : '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 14268:14268
  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - jaeger
      - currency
      - cart
      - productcatlog
      - recommended
  cart:
    build: ./cartservice
    ports:
      - 80:80
    depends_on:
      - jaeger
  currency:
    build: ./currencyservice
    ports:
      - 9000:9000
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
  recommended:
    build: ./recommendationservice
    ports:
      - 8080:8080
    depends_on:
      - cart
      - jaeger
      - currency
  productcatlog:
    build: ./productcatalogservice
    ports:
      - 4000:4000
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces      
    depends_on:
      - jaeger
      - cart
      - recommended
      - currency
  checkout:
    build: ./checkoutservice
    ports: 
      - 5050:5050
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces      
    depends_on:
      - jaeger
      - frontend
      - cart
      - currency
  payment:
    build: ./paymentservice
    ports:
      - 8011:8011
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger
      - checkout
      - currency
  shipping:
    build: ./shippingservice
    ports:
      - 50051:50051
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces      
    depends_on:
      - jaeger
      - frontend
      - cart
      - currency
      - checkout
  ad:
    build: ./adservice
    ports:
      - 9555:9555
    environment:
      - EXPORTER=jaeger
      - EXPORTER_ENDPOINT=jaeger:14250
      - SERVICE_NAME=ADSERVICE
    depends_on:
      - checkout
  email:
    build: ./emailservice
    ports:
      - 4009:4009
    depends_on:
      - jaeger
      - checkout
